export const ACTION_LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const ACTION_LOAD_SELECTED_PRODUCTS = 'LOAD_SELECTED_PRODUCTS'
export const ACTION_ADD_ORDER = 'ACTION_ADD_ORDER'
export const ACTION_REMOVE_ORDER = 'ACTION_REMOVE_ORDER'